[project]
name = "weeb-dl"
version = "1.0"
description = "Download manga/manhwa/manhua from weebcentral.com"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "notify-py>=0.3.43",
    "pikepdf>=10.7.2",
    "platformdirs>=4.10.0",
    "requests>=2.34.2",
    "ttkbootstrap>=1.20.3",
]

[tool.ruff]
line-length = 100

# ignore linter warnings related to '*' imports
[tool.ruff.lint]
ignore = ["F403", "F405"]
